# Esegui questo script nella cartella del progetto:
# cd C:\ProgettoRAG_DEV
# .\crea_config.ps1

$outPath = Join-Path (Get-Location) "config.py"
$lines = @(
    '"""'
    'config.py'
    'Configurazione centralizzata di WinSarp AI Hub.'
    'Tutti i parametri leggibili da variabili d''ambiente.'
    'Se la variabile non e'' impostata, usa il valore di default.'
    ''
    'Utilizzo:'
    '    from config import cfg'
    '    print(cfg.PORT)'
    ''
    'Override da env (esempi PowerShell):'
    '    $env:WINSARP_PORT="8503"'
    '    $env:WINSARP_HOST="0.0.0.0"'
    '"""'
    'import os'
    'from dataclasses import dataclass, field'
    ''
    ''
    ''
    '@dataclass(frozen=True)'
    'class Config:'
    ''
    '    # --------------------------------------------------------'
    '    # SERVER'
    '    # --------------------------------------------------------'
    '    # HOST: 127.0.0.1 = solo localhost (sicuro per intranet).'
    '    # Cambia in 0.0.0.0 SOLO se c''e'' un reverse proxy davanti.'
    '    HOST: str = field(default_factory=lambda: os.environ.get("WINSARP_HOST", "127.0.0.1"))'
    '    PORT: int = field(default_factory=lambda: int(os.environ.get("WINSARP_PORT", "8502")))'
    ''
    '    # --------------------------------------------------------'
    '    # PATH'
    '    # --------------------------------------------------------'
    '    BASE_DIR:         str = field(default_factory=lambda: os.path.abspath('
    '        os.environ.get("WINSARP_BASE_DIR", ".")))'
    ''
    '    @property'
    '    def DOCS_DIR(self) -> str:'
    '        return os.path.join(self.BASE_DIR, "documenti")'
    ''
    '    @property'
    '    def CHROMA_DIR(self) -> str:'
    '        return os.path.join(self.BASE_DIR, "chroma_db")'
    ''
    '    @property'
    '    def HASH_FILE(self) -> str:'
    '        return os.path.join(self.CHROMA_DIR, "docs_hashes.json")'
    ''
    '    @property'
    '    def LOGS_DIR(self) -> str:'
    '        return os.path.join(self.BASE_DIR, "logs")'
    ''
    '    # --------------------------------------------------------'
    '    # PROMPT / CHAT'
    '    # --------------------------------------------------------'
    '    PROMPT_MAX_CHARS:   int = field(default_factory=lambda: int(os.environ.get("WINSARP_PROMPT_MAX_CHARS",   "2000")))'
    '    TYPING_TIMEOUT_SEC: int = field(default_factory=lambda: int(os.environ.get("WINSARP_TYPING_TIMEOUT",    "180")))'
    '    TOKEN_TIMEOUT_SEC:  int = field(default_factory=lambda: int(os.environ.get("WINSARP_TOKEN_TIMEOUT",     "300")))'
    ''
    '    # --------------------------------------------------------'
    '    # MODELLI'
    '    # --------------------------------------------------------'
    '    DEFAULT_MODEL_ID: str = field(default_factory=lambda: os.environ.get("WINSARP_MODEL",       "qwen2.5:7b"))'
    '    EMBED_MODEL_ID:   str = field(default_factory=lambda: os.environ.get("WINSARP_EMBED_MODEL", "nomic-embed-text"))'
    ''
    '    # --------------------------------------------------------'
    '    # OLLAMA'
    '    # --------------------------------------------------------'
    '    # Ollama deve restare su localhost: non esporre mai in LAN.'
    '    OLLAMA_HOST: str = field(default_factory=lambda: os.environ.get("OLLAMA_HOST", "http://127.0.0.1:11434"))'
    ''
    '    # --------------------------------------------------------'
    '    # RAG / RETRIEVAL'
    '    # --------------------------------------------------------'
    '    SCORE_THRESHOLD_LOW: float = field(default_factory=lambda: float(os.environ.get("WINSARP_SCORE_LOW", "0.35")))'
    '    SCORE_THRESHOLD_MED: float = field(default_factory=lambda: float(os.environ.get("WINSARP_SCORE_MED", "0.55")))'
    ''
    '    # --------------------------------------------------------'
    '    # LOG'
    '    # --------------------------------------------------------'
    '    LOG_RETENTION_DAYS: int = field(default_factory=lambda: int(os.environ.get("WINSARP_LOG_RETENTION_DAYS", "30")))'
    ''
    ''
    ''
    '# Istanza globale — importa questa in tutti i moduli.'
    'cfg = Config()'
    ''
    ''
    ''
    '# ============================================================'
    '# SELF-CHECK (opzionale, eseguibile direttamente)'
    '# ============================================================'
    'if __name__ == "__main__":'
    '    print("=== WinSarp AI Hub — Config attiva ===")'
    '    print(f"  HOST             : {cfg.HOST}")'
    '    print(f"  PORT             : {cfg.PORT}")'
    '    print(f"  BASE_DIR         : {cfg.BASE_DIR}")'
    '    print(f"  DOCS_DIR         : {cfg.DOCS_DIR}")'
    '    print(f"  CHROMA_DIR       : {cfg.CHROMA_DIR}")'
    '    print(f"  HASH_FILE        : {cfg.HASH_FILE}")'
    '    print(f"  LOGS_DIR         : {cfg.LOGS_DIR}")'
    '    print(f"  PROMPT_MAX_CHARS : {cfg.PROMPT_MAX_CHARS}")'
    '    print(f"  TYPING_TIMEOUT   : {cfg.TYPING_TIMEOUT_SEC}s")'
    '    print(f"  TOKEN_TIMEOUT    : {cfg.TOKEN_TIMEOUT_SEC}s")'
    '    print(f"  DEFAULT_MODEL    : {cfg.DEFAULT_MODEL_ID}")'
    '    print(f"  EMBED_MODEL      : {cfg.EMBED_MODEL_ID}")'
    '    print(f"  OLLAMA_HOST      : {cfg.OLLAMA_HOST}")'
    '    print(f"  SCORE_LOW        : {cfg.SCORE_THRESHOLD_LOW}")'
    '    print(f"  SCORE_MED        : {cfg.SCORE_THRESHOLD_MED}")'
    '    print(f"  LOG_RETENTION    : {cfg.LOG_RETENTION_DAYS}gg")'
)

# Scrivi UTF-8 senza BOM
$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllLines($outPath, $lines, $utf8NoBom)
Write-Host "config.py creato in: $outPath" -ForegroundColor Green
python config.py
