apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ermes-knowledge.fullname" . }}-secrets
  labels:
    {{- include "ermes-knowledge.labels" . | nindent 4 }}
type: Opaque
stringData:
  ERMES_ADMIN_USERNAME: {{ .Values.secrets.adminUsername | default "admin" | quote }}
  ERMES_ADMIN_PASSWORD: {{ .Values.secrets.adminPassword | default "" | quote }}
  ERMES_AUDIT_SECRET: {{ .Values.secrets.auditSecret | default "" | quote }}
  S3_ACCESS_KEY_ID: {{ .Values.secrets.s3AccessKeyId | default "" | quote }}
  S3_SECRET_ACCESS_KEY: {{ .Values.secrets.s3SecretAccessKey | default "" | quote }}
  ERMES_STORAGE_ENCRYPTION_KEY: {{ .Values.secrets.storageEncryptionKey | default "" | quote }}
  {{- if .Values.config.auditRemoteUrl }}
  ERMES_AUDIT_REMOTE_TOKEN: {{ .Values.secrets.auditRemoteToken | default "" | quote }}
  {{- end }}
  OPENROUTER_API_KEY: {{ .Values.secrets.openrouterApiKey | default "" | quote }}
